{% set name = "crc32c" %}
{% set version = "1.1.2" %}

package:
  name: lib{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ac07840513072b7fcebda6e821068aa04889018f24e10e46181068fb214d7e56

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("libcrc32c", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
  host:
  run:

test:
  requires:
    - {{ compiler('cxx') }}  # [win and arm64]
    - cmake                 # [win and arm64]
  files:
    - consumer              # [win and arm64]
  commands:
    - test -f $PREFIX/lib/libcrc32c${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/crc32c/crc32c.h  # [unix]
    - test -f $PREFIX/lib/cmake/Crc32c/Crc32cTargets.cmake  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\crc32c.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\crc32c.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\crc32c\\crc32c.h exit 1  # [win]
    - cmake -S consumer -B consumer-build -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="%LIBRARY_PREFIX%"  # [win and arm64]
    - cmake --build consumer-build  # [win and arm64]
    - consumer-build\crc32c_consumer.exe  # [win and arm64]
    - dumpbin /headers consumer-build\crc32c_consumer.exe | findstr /I /C:"AA64 machine (ARM64)"  # [win and arm64]
    - dumpbin /headers %LIBRARY_BIN%\crc32c.dll | findstr /I /C:"AA64 machine (ARM64)"  # [win and arm64]

about:
  home: https://github.com/google/crc32c
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CRC32C implementation with support for CPU-specific acceleration instructions

extra:
  recipe-maintainers:
    - xhochy
    - tswast
